version: '3.8'
services:
  db:
    image: mysql:8
    container_name: my_sql_db
    environment:
      - MYSQL_DATABASE=mi_basedatos
      - MYSQL_USER=esteban
      - MYSQL_PASSWORD=esteban
      - MYSQL_ROOT_PASSWORD=root_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - my_network

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: spring_boot_app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/mi_basedatos
      - SPRING_DATASOURCE_USERNAME=esteban
      - SPRING_DATASOURCE_PASSWORD=esteban
    depends_on:
      - db
    networks:
      - my_network

  frontend:
    build:
      context: ./frontend/my-angular-app
      dockerfile: Dockerfile
    container_name: angular_app
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

volumes:
  db_data:
